version: '3'
services:
  tf:
    build: ./
    image: contino/terraform
    volumes:
      - type: bind
        source: ../infrastructure
        target: /opt/app
    working_dir: /opt/app
    env_file: .env
