name: build_weather_app
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "build_back_end"
    branches: [master]
    types:
      - completed
    paths:
      - '.github/workflows/build_weather_app.yml'
      - 'application/public/**'
      - 'application/src/**'
      - 'application/templates/**'
      - 'application/.env'
      - 'application/Makefile'
      - 'application/package-lock.json'
      - 'application/package.json'
      - 'application/weather-app-dockerfile'
jobs:
  build_weather_app:
    defaults:
      run:
        working-directory: ./application
    environment:
      name: approval
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      COMPOSE_FILE: "docker-compose.weather-app.yml"
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    name: Build and push docker image to Amazon ECR
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v2
      - name: Build and tag docker image
        run: make build_and_tag_docker_image
      - name: Log in to Amazon ECR
        run: make ecr_login
      - name: Push docker image to ECR
        run: make push_docker_image
