name: destroy_front_end
on:
  workflow_dispatch:
  push:
    branches:
      - destroy
    paths:
      - '.github/workflows/destroy_front_end.yml'
      - 'front_end/modules/**'
      - 'front_end/**.tf'
      
jobs:
  terraform_destroy_plan:
    defaults:
      run:
        working-directory: ./orchestration
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      COMPOSE_FILE: "docker-compose.front-end.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan       

  terraform_destroy_apply:
    defaults:
      run:
        working-directory: ./orchestration
    environment:
      name: approval
    needs: terraform_destroy_plan
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: "docker-compose.front-end.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply