name: deploy-weather-app
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'application/public/**'
      - 'application/src/**'
      - 'application/templates/**'
      - 'application/.env'
      - 'application/Makefile'
      - 'application/package-lock.json'
      - 'application/package.json'
      - 'application/weather-app-dockerfile'
jobs:
  ecr_login:
    defaults:
      run:
        working-directory: ./application
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_NAME:  ${{ secrets.ECR_REPO_NAME }} 
    steps:
    - uses: actions/checkout@v2
    - name: ECR_Login
      run: make ecr_login       

  build_docker_image:
    defaults:
      run:
        working-directory: ./application
    environment:
      name: approval
    needs: ecr_login
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_NAME:  ${{ secrets.ECR_REPO_NAME }} 
    steps:
    - uses: actions/checkout@v2
    - name: ECR_Login
      run: make ecr_login
    - name: Build_Docker_Image
      run: make build_docker_image
    
    push_docker_image:
      defaults:
        run:
          working-directory: ./application
      environment:
        name: approval
      needs: build_docker_image
      runs-on: ubuntu-latest
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECR_REPO_NAME:  ${{ secrets.ECR_REPO_NAME }}
      steps:
      - uses: actions/checkout@v2
      - name: Build_Docker_Image
        run: make build_docker_image
      - name: Push_Docker_image
        run: make push_docker_image


