name: build_weather_app
on:
  workflow_run:
    workflows: ["Deploy"]
    branches: [master]
    types:
      - completed
    paths:
      - '.github/workflows/**'
      - 'application/public/**'
      - 'application/src/**'
      - 'application/templates/**'
      - 'application/.env'
      - 'application/Makefile'
      - 'application/package-lock.json'
      - 'application/package.json'
      - 'application/weather-app-dockerfile'
jobs:
  build_weather_app:
    defaults:
      run:
        working-directory: ./application
    environment:
      name: approval
    runs-on: ubuntu-latest
    name: Build and push image to Amazon ECR
    steps:
      - name: Checkout_Repo
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        run: make ecr_login
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 

      - name: Build weather-app image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        run: make build_docker_image

      - name: Push weather-app image to ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO_NAME: ${{ secrets.ECR_REPO_NAME }}
        run: make push_docker_image
